// Code generated by protoc-gen-go.
// source: base.proto
// DO NOT EDIT!

/*
Package Carrier is a generated protocol buffer package.

It is generated from these files:
	base.proto
	distribute_ack.proto
	distribute_cross.proto
	distribute_ctl.proto
	distribute_freset.proto
	distribute_location.proto
	distribute_logrt.proto
	distribute_lowpset.proto
	distribute_message.proto
	distribute.proto
	distribute_reqp.proto
	distribute_srvset.proto
	distribute_tearchk.proto
	distribute_upgrade.proto
	report_ack.proto
	report_location.proto
	report_login.proto
	report_lowp.proto
	report.proto
	report_receipt.proto
	report_upresult.proto

It has these top-level messages:
	Header
	LocationExtra
	DistributeAck
	DistributeCross
	DistributeCtl
	DistributeFreset
	DistributeLocation
	DistributeLogRt
	DistributeLowpset
	DistributeMessage
	Distribute
	DistributeReqp
	DistributeSrvset
	DistributeTearchk
	DistributeUpgrade
	ReportAck
	ReportLocation
	ReportLogin
	ReportLowp
	Report
	ReportReceipt
	ReportUpresult
*/
package Carrier

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	// app id 程序标志，使用场景:多个程序调用同一个服务，该服务可以记录每个程序的调用情况
	Appid string `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
	// 消息的投递方 一般情况下认为消息的投递方也是消息经过服务处理后的错误处理方
	From string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	// 消息的目的方
	To string `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *Header) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Header) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type LocationExtra struct {
	// imei
	Imei string `protobuf:"bytes,1,opt,name=imei" json:"imei,omitempty"`
	// serial
	Serial string `protobuf:"bytes,2,opt,name=serial" json:"serial,omitempty"`
	// terminal status  "00" 正常 ”x1" 拆卸 "1x" 低电
	TerminalStatus string `protobuf:"bytes,3,opt,name=terminal_status" json:"terminal_status,omitempty"`
	// time  格式为YYMMDD-HHMMSS
	Time string `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
	// 电量
	Batt string `protobuf:"bytes,5,opt,name=batt" json:"batt,omitempty"`
	// 0 终端主动上报 1 终端被动上报 2 终端位置补报 3 超圈检测
	PosReason string `protobuf:"bytes,6,opt,name=pos_reason" json:"pos_reason,omitempty"`
	// 定位类型 0=GPS位置，1=基站位置,2=wifi定位
	PosType string `protobuf:"bytes,7,opt,name=pos_type" json:"pos_type,omitempty"`
}

func (m *LocationExtra) Reset()                    { *m = LocationExtra{} }
func (m *LocationExtra) String() string            { return proto.CompactTextString(m) }
func (*LocationExtra) ProtoMessage()               {}
func (*LocationExtra) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LocationExtra) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *LocationExtra) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *LocationExtra) GetTerminalStatus() string {
	if m != nil {
		return m.TerminalStatus
	}
	return ""
}

func (m *LocationExtra) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *LocationExtra) GetBatt() string {
	if m != nil {
		return m.Batt
	}
	return ""
}

func (m *LocationExtra) GetPosReason() string {
	if m != nil {
		return m.PosReason
	}
	return ""
}

func (m *LocationExtra) GetPosType() string {
	if m != nil {
		return m.PosType
	}
	return ""
}

func init() {
	proto.RegisterType((*Header)(nil), "Carrier.Header")
	proto.RegisterType((*LocationExtra)(nil), "Carrier.LocationExtra")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x34, 0x8f, 0x41, 0x4a, 0xc5, 0x40,
	0x0c, 0x40, 0x69, 0x6d, 0xa7, 0x1a, 0xac, 0xca, 0x6c, 0x9c, 0xa5, 0x74, 0xe5, 0x4a, 0x10, 0x8f,
	0x20, 0x82, 0x0b, 0xef, 0x50, 0x52, 0x1b, 0x21, 0xd0, 0x69, 0x86, 0x4c, 0x04, 0xbd, 0x81, 0xc7,
	0x96, 0x99, 0xdf, 0xbf, 0xcb, 0x7b, 0xe4, 0x05, 0x02, 0xb0, 0x60, 0xa6, 0xa7, 0xa4, 0x62, 0xe2,
	0x87, 0x57, 0x54, 0x65, 0xd2, 0xe9, 0x19, 0xdc, 0x3b, 0xe1, 0x4a, 0xea, 0x47, 0xe8, 0x31, 0x25,
	0x5e, 0x43, 0xf3, 0xd0, 0x3c, 0x5e, 0xf9, 0x6b, 0xe8, 0xbe, 0x54, 0x62, 0x68, 0x2b, 0x01, 0xb4,
	0x26, 0xe1, 0xa2, 0xcc, 0xd3, 0x5f, 0x03, 0xe3, 0x87, 0x7c, 0xa2, 0xb1, 0xec, 0x6f, 0x3f, 0xa6,
	0x58, 0x76, 0x39, 0x12, 0x1f, 0xe5, 0x0d, 0xb8, 0x4c, 0xca, 0xb8, 0x1d, 0xed, 0x3d, 0xdc, 0x1a,
	0x69, 0xe4, 0x1d, 0xb7, 0x39, 0x1b, 0xda, 0x77, 0x3e, 0x1d, 0x2a, 0x99, 0x71, 0xa4, 0xd0, 0x9d,
	0x69, 0x41, 0xb3, 0xd0, 0x57, 0xf2, 0x00, 0x49, 0xf2, 0xac, 0x84, 0x59, 0xf6, 0xe0, 0xaa, 0xbb,
	0x83, 0xcb, 0xe2, 0xec, 0x37, 0x51, 0x18, 0x8a, 0x59, 0x5c, 0xfd, 0xe6, 0xe5, 0x3f, 0x00, 0x00,
	0xff, 0xff, 0xd5, 0xdf, 0x0f, 0xe3, 0xdb, 0x00, 0x00, 0x00,
}
