// Code generated by protoc-gen-go.
// source: report_login.proto
// DO NOT EDIT!

package Carrier

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ReportLogin struct {
	// imei
	Imei string `protobuf:"bytes,1,opt,name=imei" json:"imei,omitempty"`
	// 设备IMSI
	Imsi string `protobuf:"bytes,2,opt,name=imsi" json:"imsi,omitempty"`
	// 设备类型
	DeviceType string `protobuf:"bytes,3,opt,name=device_type" json:"device_type,omitempty"`
	// 协议版本
	Protocol string `protobuf:"bytes,4,opt,name=protocol" json:"protocol,omitempty"`
	// 时间
	// time 格式为YYMMDD-HHMMSS
	Time string `protobuf:"bytes,5,opt,name=time" json:"time,omitempty"`
}

func (m *ReportLogin) Reset()                    { *m = ReportLogin{} }
func (m *ReportLogin) String() string            { return proto.CompactTextString(m) }
func (*ReportLogin) ProtoMessage()               {}
func (*ReportLogin) Descriptor() ([]byte, []int) { return fileDescriptor16, []int{0} }

func (m *ReportLogin) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *ReportLogin) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

func (m *ReportLogin) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *ReportLogin) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *ReportLogin) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*ReportLogin)(nil), "Carrier.ReportLogin")
}

func init() { proto.RegisterFile("report_login.proto", fileDescriptor16) }

var fileDescriptor16 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4a, 0x2d, 0xc8,
	0x2f, 0x2a, 0x89, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x77, 0x4e, 0x2c, 0x2a, 0xca, 0x4c, 0x2d, 0x52, 0x8a, 0xe3, 0xe2, 0x0e, 0x02, 0x4b, 0xfb, 0x80,
	0x64, 0x85, 0x78, 0xb8, 0x58, 0x32, 0x73, 0x53, 0x33, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x21,
	0xbc, 0xe2, 0x4c, 0x09, 0x26, 0x30, 0x4f, 0x98, 0x8b, 0x3b, 0x25, 0xb5, 0x2c, 0x33, 0x39, 0x35,
	0xbe, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x19, 0x2c, 0x28, 0xc0, 0xc5, 0x01, 0x36, 0x31, 0x39, 0x3f,
	0x47, 0x82, 0x05, 0xa6, 0xa9, 0x24, 0x33, 0x37, 0x55, 0x82, 0x15, 0xc4, 0x4b, 0x62, 0x03, 0xcb,
	0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x1b, 0x9e, 0x42, 0x85, 0x00, 0x00, 0x00,
}
