// Code generated by protoc-gen-go.
// source: base.proto
// DO NOT EDIT!

/*
Package Lbs is a generated protocol buffer package.

It is generated from these files:
	base.proto
	in.proto
	out.proto

It has these top-level messages:
	Header
	WifiCell
	StationCell
	Report
	Distribute
*/
package Lbs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	// app id 程序标志，使用场景:多个程序调用同一个服务，该服务可以记录每个程序的调用情况
	Appid string `protobuf:"bytes,1,opt,name=appid" json:"appid,omitempty"`
	// 消息的投递方 一般情况下认为消息的投递方也是消息经过服务处理后的错误处理方
	From string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	// 消息的目的方
	To string `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *Header) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Header) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func init() {
	proto.RegisterType((*Header)(nil), "Lbs.Header")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xf6, 0x49, 0x2a, 0x56, 0x32, 0xe4, 0x62, 0xf3,
	0x48, 0x4d, 0x4c, 0x49, 0x2d, 0x12, 0xe2, 0xe5, 0x62, 0x4d, 0x2c, 0x28, 0xc8, 0x4c, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x14, 0xe2, 0xe1, 0x62, 0x49, 0x2b, 0xca, 0xcf, 0x95, 0x60, 0x02, 0xf3,
	0xb8, 0xb8, 0x98, 0x4a, 0xf2, 0x25, 0x98, 0x41, 0xec, 0x24, 0x36, 0xb0, 0x76, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc9, 0x97, 0x8b, 0xde, 0x4c, 0x00, 0x00, 0x00,
}
